<?php if ($this->buttonEnabled()): ?>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript">
        jQuery.noConflict();
        
        var dataOptions = {
            storeId: <?php echo $this->getStoreId(); ?>,
            customersChunks: <?php echo $this->getCustomerChunks(); ?>,
            categoriesChunks: <?php echo $this->getCategoryChunks(); ?>,
            productsChunks: <?php echo $this->getProductChunks(); ?>,
            ordersChunks: <?php echo $this->getOrderChunks(); ?>,
            importType: 'customers',
            percentage: 100,
            form_key: window.FORM_KEY, // add form_key for magento controller check
        };
        
        function sync_chunk(chunkId, importType, retryStatus) {
            dataOptions.chunkId = chunkId;
            
            if (importType == 'customers' && chunkId == 0) {
                jQuery('#metrilo_button').addClass('disabled').attr('disabled', 'disabled').text('Importing customers');
            }
            
            var progress_percents = Math.round(chunkId * this.dataOptions.percentage);
            this.update_importing_message('Please wait... ' + progress_percents + '% done', true);

            this.ajax_post_with_retry('<?php echo $this->getAjaxUrl(); ?>', this.dataOptions, 3, function() {
                var newChunkId = chunkId + 1;
                if(retryStatus){
                    newChunkId++;
                }
                
                switch (importType) {
                    case 'customers':
                        this.import_type(newChunkId, dataOptions, 'customers', 'categories');
                        break;
                    case 'categories':
                        this.import_type(newChunkId, dataOptions, 'categories', 'deletedProducts');
                        break;
                    case 'deletedProducts':
                        this.import_type(newChunkId, dataOptions, 'deletedProducts', 'products');
                        break;
                    case 'products':
                        this.import_type(newChunkId, dataOptions, 'products', 'orders');
                        break;
                    case 'orders':
                        this.import_type(newChunkId, dataOptions, 'orders', null);
                        break;
                    default:
                        return false;
                }
            });
        }
        
        function ajax_post_with_retry(url, data, retryCount, callback) {
            if(retryCount) {
                jQuery.post(url, data, function(response) {
                    callback();
                }).fail(function () {
                    console.log('fail!', data, retryCount);
                    setTimeout(function() {
                        this.ajax_post_with_retry(url, data, retryCount - 1 , callback);
                    }, 5000);
                })
            } else {
                this.sync_chunk(data.chunkId + 1, data.importType, true);
            }
        }
        
        function import_type(newChunkId, dataOptions, current, next) {
            if (dataOptions[`${current}Chunks`] > 0) {
                dataOptions.percentage = (100 / dataOptions[`${current}Chunks`]);
            }
            
            var hasMoreChunks = newChunkId < dataOptions[`${current}Chunks`];
            
            if(hasMoreChunks) {
                this.sync_chunk(newChunkId, dataOptions.importType, false);
            } else {
                if(current == 'orders') {
                    this.update_importing_message(
                        "<span style='color: green;'>" +
                        'Done! Please expect up to 30 minutes for your historical data to appear in Metrilo.' +
                        "</span>"
                    );
                    jQuery('#metrilo_button').removeClass('disabled').addClass('success').text('Finished Import.');
                } else {
                    jQuery('#metrilo_button').text((`Importing ${next}`));
                    dataOptions.importType = next;
                    this.sync_chunk(0, dataOptions.importType, false);
                }
            }
        }
        
        function update_importing_message(message, show_loader) {
            if (show_loader)
                message = '<img src="<?php echo $this->getSkinUrl("metrilo/loader.gif"); ?>" />' + message;
            jQuery('#metrilo_import_status').html(message);
        }
    </script>

    <?php if ($this->getStoreId()): ?>
        <div style="float: left;">
            <h3>Importing your historical data</h3>
            <p>
                This tool helps you sync all your categories, products, orders and customers to Metrilo
                and can take <strong>up to 20 minutes</strong> to complete. <br />
                It will not affect your website's performance at all since it sends your orders to your
                Metrilo account in small chunks.  <br /><br />
                Make sure to <strong>not close this page</strong> while importing. Coffee, maybe?
            </p>
        </div>
        <div style="clear:both"></div>
        <?php echo $this->getButtonHtml() ?>
        <div style="clear:both"></div>
        <div id="metrilo_import_status"></div>
        <div style="clear:both"></div>
    <?php else: ?>
        <div style="float: left;">
            <p>
                In order to import your data, please pick a store from
                <strong>Current Configuration Scope</strong> on the top left
                to make the import for the selected store.
            </p>
        </div>
        <div style="clear:both"></div>
    <?php endif; ?>
<?php endif; ?>
