<?php if ($this->buttonEnabled()): ?>
    <?php $import = $this->getImport(); ?>
    <?php $storeId = $import->getStoreId(); ?>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript">
        jQuery.noConflict();

        function import_metrilo() {
            var storeId     = <?php echo $storeId; ?>;
            var totalChunks = <?php echo $import->getChunks($storeId); ?>;
            var chunkPercentage = 100;
            if(totalChunks > 0){
                var chunkPercentage = (100 / totalChunks);
            }
            // Update button state and text
            jQuery('#metrilo_button').addClass('disabled').attr('disabled', 'disabled').text('Importing orders');

            var sync_chunk = function(chunkId){
                progress_percents = Math.round(chunkId * chunkPercentage);
                update_importing_message('Please wait... '+progress_percents+'% done', true);

                // add form_key for magento controller check
                data = {
                    'storeId': storeId,
                    'chunkId': chunkId,
                    'totalChunks': totalChunks,
                    'form_key': window.FORM_KEY
                };
                jQuery.post('<?php echo $this->getAjaxUrl(); ?>', data, function(response) {
                    new_chunk_id = chunkId + 1;
                    if(new_chunk_id < totalChunks){
                        setTimeout(function() {
                            sync_chunk(new_chunk_id);
                        }, 100);
                    }else{
                        update_importing_message("<span style='color: green;'>Done! Please expect up to 30 minutes for your historical data to appear in Metrilo.</span>", false);
                        jQuery('#metrilo_button').removeClass('disabled').addClass('success').text('Orders imported');
                    }

                });

            }

            var update_importing_message = function(message, show_loader){
                if (show_loader)
                    message = '<img src="<?php echo $this->getSkinUrl("metrilo/loader.gif"); ?>" />' + message;
                jQuery('#metrilo_import_status').html(message);
            }
            sync_chunk(0);
        }
    </script>

    <?php if ($this->showInStore()): ?>
        <div style="float: left;">
            <h3>Importing your orders and customers</h3>
            <p>
                This tool helps you sync all your orders and customers to Metrilo and can take <strong>up to 20 minutes</strong> to complete. <br />
                It will not affect your website's performance at all since it sends your orders to your Metrilo account in small chunks.  <br /><br />
                Make sure to <strong>not close this page</strong> while importing. Coffee, maybe?
            </p>
        </div>
        <div style="clear:both"></div>
        <?php echo $this->getButtonHtml() ?>
        <div style="clear:both"></div>
        <div id="metrilo_import_status"></div>
        <div style="clear:both"></div>
    <?php else: ?>
        <div style="float: left;">
            <p>
                In order to import your orders, please pick a store from
                <strong>Current Configuration Scope</strong> on the top left
                to make the import for the selected store.
            </p>
        </div>
        <div style="clear:both"></div>
    <?php endif; ?>
<?php endif; ?>
