<?php $events = $this->getEvents(); ?>
<?php $url    = $this->getLibraryUrl(); ?>
<script type="text/javascript" async="true" src="<?php echo $url; ?>"></script>
<script type="text/javascript">
    (function() {
        const f = function () {
            <?php
            foreach($events as $event) {
                echo html_entity_decode($event);
            }
            ?>
        };
        if (typeof window.metrilo !== 'undefined') {
            f();
        } else {
            window.metriloQueue = window.metriloQueue || [];
            window.metriloQueue.push(f);
        }
    })();
</script>
